print("Calculating the Perimeter of a rectangle")
a=int(input("Enter the length of the rectangle:"))
b=int(input("Enter the breadth of the rectangle:"))
c=2*(a+b)
print("The perimeter of the rectangle is:" ,c)
